### PR TITLE
Support for Socket.ip_address_list, Addrinfo, and a near total rewrite

### PR DESCRIPTION
**Pull request by YorickPeterse**
This is still a work in progress, but once done should add support for `Socket.ip_address_list`.

Socket:

* [x] `Socket.ip_address_list`
* [x] Better tests (if possible) for `Socket.ip_address_list`

## Addrinfo

* [x] `Addrinfo.foreach`
* [x] `Addrinfo.getaddrinfo`
* [x] `Addrinfo.ip`
* [x] `Addrinfo.tcp`
* [x] `Addrinfo.udp`
* [x] `Addrinfo.unix`
* [x] `Addrinfo#initialize`
* [x] `Addrinfo#afamily`
* [x] `Addrinfo#bind`
* [x] `Addrinfo#canonname`
* [x] `Addrinfo#connect`
* [x] `Addrinfo#connect_from`
* [x] `Addrinfo#connect_to`
* [x] `Addrinfo#family_addrinfo`
* [x] `Addrinfo#getnameinfo`
* [x] `Addrinfo#inspect`
* [x] `Addrinfo#inspect_sockaddr`
* [x] `Addrinfo#ip?`
* [x] `Addrinfo#ip_address`
* [x] `Addrinfo#ip_port`
* [x] `Addrinfo#ip_unpack`
* [x] `Addrinfo#ipv4?`
* [x] `Addrinfo#ipv4_loopback?`
* [x] `Addrinfo#ipv4_multicast?`
* [x] `Addrinfo#ipv4_private?`
* [x] `Addrinfo#ipv6?`
* [x] `Addrinfo#ipv6_linklocal?`
* [x] `Addrinfo#ipv6_loopback?`
* [x] `Addrinfo#ipv6_mc_global?`
* [x] `Addrinfo#ipv6_mc_linklocal?`
* [x] `Addrinfo#ipv6_mc_nodelocal?`
* [x] `Addrinfo#ipv6_mc_orglocal?`
* [x] `Addrinfo#ipv6_mc_sitelocal?`
* [x] `Addrinfo#ipv6_multicast?`
* [x] `Addrinfo#ipv6_sitelocal?`
* [x] `Addrinfo#ipv6_to_ipv4`
* [x] `Addrinfo#ipv6_unique_local?`
* [x] `Addrinfo#ipv6_unspecified?`
* [x] `Addrinfo#ipv6_v4compat?`
* [x] `Addrinfo#ipv6_v4mapped?`
* [x] `Addrinfo#listen`
* [x] `Addrinfo#marshal_dump`
* [x] `Addrinfo#marshal_load`
* [x] `Addrinfo#pfamily`
* [x] `Addrinfo#protocol`
* [x] `Addrinfo#socktype`
* [x] `Addrinfo#to_s`
* [x] `Addrinfo#to_sockaddr`
* [x] `Addrinfo#unix?`
* [x] `Addrinfo#unix_path`

## Socket Spec Status

Specs and implementations of the following methods should be verified and optionally updated/re-factored should they not be compliant with MRI 2.x:

* [x] `BasicSocket#close_read`
* [x] `BasicSocket#close_write`
* [x] `BasicSocket#connect_address`
* [x] `BasicSocket#do_not_reverse_lookup=`
* [x] `BasicSocket#do_not_reverse_lookup`
* [x] `BasicSocket#getpeereid`
* [x] `BasicSocket#getpeername`
* [x] `BasicSocket#getsockname`
* [x] `BasicSocket#getsockopt`
* [x] `BasicSocket#local_address`
* [x] `BasicSocket#recv_nonblock`
* [x] `BasicSocket#recv`
* [x] `BasicSocket#recvmsg_nonblock`
* [x] `BasicSocket#recvmsg`
* [x] `BasicSocket#remote_address`
* [x] `BasicSocket#send`
* [x] `BasicSocket#sendmsg_nonblock`
* [x] `BasicSocket#sendmsg`
* [x] `BasicSocket#setsockopt`
* [x] `BasicSocket#shutdown`
* [x] `BasicSocket.for_fd`
* [x] `IPSocket.getaddress`
* [x] `IPSocket#addr`
* [x] `IPSocket#peeraddr`
* [x] `IPSocket#recvfrom`
* [x] `Socket.getaddrinfo`
* [x] `Socket#accept_nonblock`
* [x] `Socket#accept`
* [x] `Socket#bind`
* [x] `Socket#connect_nonblock`
* [x] `Socket#connect`
* [x] `Socket#ipv6only!`
* [x] `Socket#listen`
* [x] `Socket#recvfrom_nonblock`
* [x] `Socket#recvfrom`
* [x] `Socket#sysaccept`
* [x] `TCPServer#accept_nonblock`
* [x] `TCPServer#accept`
* [x] `TCPServer#listen`
* [x] `TCPServer#sysaccept`
* [x] `UDPSocket#bind`
* [x] `UDPSocket#connect`
* [x] `UDPSocket#recvfrom_nonblock`
* [x] `UDPSocket#send`
* [x] `UNIXServer#accept_nonblock`
* [x] `UNIXServer#accept`
* [x] `UNIXServer#listen`
* [x] `UNIXServer#sysaccept`
* [x] `UNIXSocket#addr`
* [x] `UNIXSocket#path`
* [x] `UNIXSocket#peeraddr`
* [x] `UNIXSocket#recv_io`
* [x] `UNIXSocket#recvfrom`
* [x] `UNIXSocket#send_io`
* [x] `TCPSocket.gethostbyname`
* [x] `TCPSocket#initialize`
* [x] `TCPSocket#send`
* [x] `TCPSocket#local_address`
* [x] `TCPSocket#remote_address`
* [x] Refactor `TCPSocket#tcp_setup`, removing it entirely if possible
* [x] `IPSocket#recvfrom_nonblock`

Output generated using:

    ruby -r socket -e '[BasicSocket, Socket, IPSocket, TCPSocket, UDPSocket, UNIXSocket, TCPServer, UNIXServer].each { |const| puts const.instance_methods(false).map { |m| "#{const}##{m}" } }'

## Socket::AncillaryData

* [x] `Socket::AncillaryData.int`
* [x] `Socket::AncillaryData.unix_rights`
* [x] `Socket::AncillaryData.ip_pktinfo`
* [x] `Socket::AncillaryData.ipv6_pktinfo`
* [x] `Socket::AncillaryData#initialize`
* [x] ~~`Socket::AncillaryData#inspect`~~: not going to mimic this as the MRI implementation is a PITA (https://github.com/ruby/ruby/blob/d2e48a3f01d9ce2fa6fd860ad5bd2fee28e29e66/ext/socket/ancdata.c#L953-L1076)
* [x] `Socket::AncillaryData#family`
* [x] `Socket::AncillaryData#level`
* [x] `Socket::AncillaryData#type`
* [x] `Socket::AncillaryData#data`
* [x] `Socket::AncillaryData#cmsg_is?`
* [x] `Socket::AncillaryData#int`
* [x] `Socket::AncillaryData#unix_rights`
* [x] ~~`Socket::AncillaryData#timestamp`~~ with the decision to not support ancillary data I'm not going to bother implementing this method as I have no idea where it would get its data from any way.
* [x] `Socket::AncillaryData#ip_pktinfo`
* [x] `Socket::AncillaryData#ipv6_pktinfo`
* [x] `Socket::AncillaryData#ipv6_pktinfo_addr`
* [x] `Socket::AncillaryData#ipv6_pktinfo_ifindex`

## Specs to verify

* [x] spec/addrinfo/afamily_spec.rb
* [x] spec/addrinfo/bind_spec.rb
* [x] spec/addrinfo/canonname_spec.rb
* [x] spec/addrinfo/connect_from_spec.rb
* [x] spec/addrinfo/connect_spec.rb
* [x] spec/addrinfo/connect_to_spec.rb
* [x] spec/addrinfo/family_addrinfo_spec.rb
* [x] spec/addrinfo/foreach_spec.rb
* [x] spec/addrinfo/getaddrinfo_spec.rb
* [x] spec/addrinfo/getnameinfo_spec.rb
* [x] spec/addrinfo/initialize_spec.rb
* [x] spec/addrinfo/inspect_sockaddr_spec.rb
* [x] spec/addrinfo/inspect_spec.rb
* [x] spec/addrinfo/ip_address_spec.rb
* [x] spec/addrinfo/ip_port_spec.rb
* [x] spec/addrinfo/ip_spec.rb
* [x] spec/addrinfo/ip_unpack_spec.rb
* [x] spec/addrinfo/ipv4_loopback_spec.rb
* [x] spec/addrinfo/ipv4_multicast_spec.rb
* [x] spec/addrinfo/ipv4_private_spec.rb
* [x] spec/addrinfo/ipv4_p_spec.rb
* [x] spec/addrinfo/ipv6_linklocal_spec.rb
* [x] spec/addrinfo/ipv6_loopback_spec.rb
* [x] spec/addrinfo/ipv6_mc_global_spec.rb
* [x] spec/addrinfo/ipv6_mc_linklocal_spec.rb
* [x] spec/addrinfo/ipv6_mc_nodelocal_spec.rb
* [x] spec/addrinfo/ipv6_mc_orglocal_spec.rb
* [x] spec/addrinfo/ipv6_mc_sitelocal_spec.rb
* [x] spec/addrinfo/ipv6_multicast_spec.rb
* [x] spec/addrinfo/ipv6_p_spec.rb
* [x] spec/addrinfo/ipv6_sitelocal_spec.rb
* [x] spec/addrinfo/ipv6_to_ipv4_spec.rb
* [x] spec/addrinfo/ipv6_unspecified_spec.rb
* [x] spec/addrinfo/ipv6_v4compat_spec.rb
* [x] spec/addrinfo/ipv6_v4mapped_spec.rb
* [x] spec/addrinfo/listen_spec.rb
* [x] spec/addrinfo/marshal_dump_spec.rb
* [x] spec/addrinfo/marshal_load_spec.rb
* [x] spec/addrinfo/pfamily_spec.rb
* [x] spec/addrinfo/protocol_spec.rb
* [x] spec/addrinfo/socktype_spec.rb
* [x] spec/addrinfo/tcp_spec.rb
* [x] spec/addrinfo/to_sockaddr_spec.rb
* [x] spec/addrinfo/to_s_spec.rb
* [x] spec/addrinfo/udp_spec.rb
* [x] spec/addrinfo/unix_path_spec.rb
* [x] spec/addrinfo/unix_p_spec.rb
* [x] spec/addrinfo/unix_spec.rb
* [x] spec/basicsocket/close_read_spec.rb
* [x] spec/basicsocket/close_write_spec.rb
* [x] spec/basicsocket/connect_address_spec.rb
* [x] spec/basicsocket/do_not_reverse_lookup_spec.rb
* [x] spec/basicsocket/for_fd_spec.rb
* [x] spec/basicsocket/getpeereid_spec.rb
* [x] spec/basicsocket/getpeername_spec.rb
* [x] spec/basicsocket/getsockname_spec.rb
* [x] spec/basicsocket/getsockopt_spec.rb
* [x] spec/basicsocket/recvmsg_nonblock_spec.rb
* [x] spec/basicsocket/recvmsg_spec.rb
* [x] spec/basicsocket/recv_nonblock_spec.rb
* [x] spec/basicsocket/recv_spec.rb
* [x] spec/basicsocket/sendmsg_nonblock_spec.rb
* [x] spec/basicsocket/sendmsg_spec.rb
* [x] spec/basicsocket/send_spec.rb
* [x] spec/basicsocket/setsockopt_spec.rb
* [x] spec/basicsocket/shutdown_spec.rb
* [x] spec/ipsocket/addr_spec.rb
* [x] spec/ipsocket/getaddress_spec.rb
* [x] spec/ipsocket/peeraddr_spec.rb
* [x] spec/ipsocket/recvfrom_spec.rb
* [x] spec/option/int_spec.rb
* [x] spec/option/linger_spec.rb
* [x] spec/option/new_spec.rb
* [x] spec/socket/accept_nonblock_spec.rb
* [x] spec/socket/accept_spec.rb
* [x] spec/socket/ancillary_data/cmsg_is_p_spec.rb
* [x] spec/socket/ancillary_data/data_spec.rb
* [x] spec/socket/ancillary_data/family_spec.rb
* [x] spec/socket/ancillary_data/initialize_spec.rb
* [x] spec/socket/ancillary_data/int_spec.rb
* [x] spec/socket/ancillary_data/ip_pktinfo_spec.rb
* [x] spec/socket/ancillary_data/ipv6_pktinfo_addr_spec.rb
* [x] spec/socket/ancillary_data/ipv6_pktinfo_ifindex_spec.rb
* [x] spec/socket/ancillary_data/ipv6_pktinfo_spec.rb
* [x] spec/socket/ancillary_data/level_spec.rb
* [x] spec/socket/ancillary_data/type_spec.rb
* [x] spec/socket/ancillary_data/unix_rights_spec.rb
* [x] spec/socket/bind_spec.rb
* [x] spec/socket/connect_nonblock_spec.rb
* [x] spec/socket/connect_spec.rb
* [x] spec/socket/constants_spec.rb
* [x] spec/socket/for_fd_spec.rb
* [x] spec/socket/getaddrinfo_spec.rb
* [x] spec/socket/gethostbyaddr_spec.rb
* [x] spec/socket/gethostbyname_spec.rb
* [x] spec/socket/gethostname_spec.rb
* [x] spec/socket/getnameinfo_spec.rb
* [x] spec/socket/getservbyname_spec.rb
* [x] spec/socket/ip_address_list_spec.rb
* [x] spec/socket/ipv6only_bang_spec.rb
* [x] spec/socket/listen_spec.rb
* [x] spec/socket/local_address_spec.rb
* [x] spec/socket/new_spec.rb
* [x] spec/socket/pack_sockaddr_in_spec.rb
* [x] spec/socket/pack_sockaddr_un_spec.rb
* [x] spec/socket/pair_spec.rb
* [x] spec/socket/recvfrom_nonblock_spec.rb
* [x] spec/socket/recvfrom_spec.rb
* [x] spec/socket/remote_address_spec.rb
* [x] spec/socket/socketpair_spec.rb
* [x] spec/socket/socket_spec.rb
* [x] spec/socket/sysaccept_spec.rb
* [x] spec/socket/unpack_sockaddr_in_spec.rb
* [x] spec/socket/unpack_sockaddr_un_spec.rb
* [x] spec/tcpserver/accept_nonblock_spec.rb
* [x] spec/tcpserver/accept_spec.rb
* [x] spec/tcpserver/initialize_spec.rb
* [x] spec/tcpserver/listen_spec.rb
* [x] spec/tcpserver/sysaccept_spec.rb
* [x] spec/tcpsocket/gethostbyname_spec.rb
* [x] spec/tcpsocket/initialize_spec.rb
* [x] spec/tcpsocket/local_address_spec.rb
* [x] spec/tcpsocket/recv_spec.rb
* [x] spec/tcpsocket/remote_address_spec.rb
* [x] spec/udpsocket/bind_spec.rb
* [x] spec/udpsocket/connect_spec.rb
* [x] spec/udpsocket/initialize_spec.rb
* [x] spec/udpsocket/inspect_spec.rb
* [x] spec/udpsocket/local_address_spec.rb
* [x] spec/udpsocket/recvfrom_nonblock_spec.rb
* [x] spec/udpsocket/remote_address_spec.rb
* [x] spec/udpsocket/send_spec.rb
* [x] spec/unixserver/accept_nonblock_spec.rb
* [x] spec/unixserver/accept_spec.rb
* [x] spec/unixserver/initialize_spec.rb
* [x] spec/unixserver/listen_spec.rb
* [x] spec/unixserver/sysaccept_spec.rb
* [x] spec/unixsocket/addr_spec.rb
* [x] spec/unixsocket/initialize_spec.rb
* [x] spec/unixsocket/local_address_spec.rb
* [x] spec/unixsocket/path_spec.rb
* [x] spec/unixsocket/peeraddr_spec.rb
* [x] spec/unixsocket/recvfrom_spec.rb
* [x] spec/unixsocket/recv_io_spec.rb
* [x] spec/unixsocket/remote_address_spec.rb
* [x] spec/unixsocket/send_io_spec.rb
* [x] spec/unixsocket/socketpair_spec.rb

## General

* [x] Use the right sockaddr structs for IPv4, IPv6, and Unix sockets.
* [x] Stop using `IO::Socketable` (and remove from Rubinius once no longer used)

### CODE REVIEW

**Comment by YorickPeterse** [comment]
Note: this requires Rbx master since it adds a few new struct configurations this PR relies on.

**Comment by YorickPeterse** [comment]
Note to self: I'm mixing `afamily` and `pfamily` in various specs. For example, `afamily` indeed is `AF_INET` but it's `pfamily` that returns `PF_UNSPEC` by default.

**Comment by YorickPeterse** [comment]
Redmine issues that revealed the above:

* https://bugs.ruby-lang.org/issues/10907
* https://bugs.ruby-lang.org/issues/10908

**Comment by YorickPeterse** [comment]
@brixen @jemc @sshao @jc00ke @vconcepcion Spamming all of you about this: currently I'd say about 30% of the work is done, but looking at my schedule for the coming weeks I don't think I'll have much time to continue on this. That and it's quite boring to be honest, so motivation to spend my weekends on this is rather lacking.

As such, if anybody wants to jump in and help (or finish it), please do so. Most of the work I've done so far is mainly based on MRI's behaviour as well as the RDoc documentation. I also think the above list of checkboxes is up to date with the list of commits, this should make it a little bit easier to see what remains to be done.

**Comment by jemc** [comment]
I can help with some of this.
@brixen - can I get push access to this repo so I can push directly to this branch?

**Comment by YorickPeterse** [comment]
@jemc I've added you to the maintainers team, which should give you enough push access.

**Comment by digitalextremist** [comment]
@YorickPeterse I've experimented with your branch, and adding `Addrinfo#to_sockaddr` .. but I've noticed that for some reason if you pass in port `0` for a `tcp` socket, it will not auto-assign an available port. If needed I'll spin this off into its own ticket and look at further.

**Comment by YorickPeterse** [comment]
@digitalextremist You left a comment but removed it afterwards by the looks of it. What was it about?

**Comment by digitalextremist** [comment]
Caught me. I made a mistaken assumption about `Addrinfo#ip_port` then caught myself. I was expecting `Socket#local_address#ip_port`

So I added `Socket#local_address` and another method I can't recall right now, but no tests yet. After that it worked as I expected. I'm trying to pull available ports by passing port `0`

**Comment by YorickPeterse** [comment]
Ah right, the Socket code is quite confusing mainly due to the naming of things.

**Comment by digitalextremist** [comment]
@YorickPeterse yeah. That's for sure. But all the methods to connect this all together seem to be there.

Ok, now I can see my changelog:

* Fixed: `Socket.bind`
* Fixed: `Addrinfo.tcp`
* Added: `Addrinfo#to_sockaddr`
* Added: `Socket#local_address`

There are some logical easy ones caused by that, like `Socket#remote_address`

@brixen rekindled my interest in `Rubinius` so I'm making my existing applications compatible.

**Comment by YorickPeterse** [comment]
TODO list for `Addrinfo#initialize` for the weekend:

* [ ] Add extra tests for `Addrinfo#initialize` (if any are still missing) to make sure it truly behaves like MRI
* [ ] Use a constant Array for the various if statements that check for multiple values, this constant should be scoped somewhere under `RubySL::Socket`
* [ ] Use somewhat more meaningful error messages instead of just "Unsupported protocol family"

**Comment by YorickPeterse** [comment]
Personal note: with some tweaking I should be able to move `local_address` and `remote_address` into the `BasicSocket` class so the methods only have to be implemented once. This however requires that all socket classes some expose:

* The address family (this can be extract from the underlying IO descriptor)
* The socket type (this can be hard-coded in the constructor method)

**Comment by brixen** [comment]
@YorickPeterse could we split Addrinfo into its own PR since that's where the bulk of the remaining work appears to be (from looking at the checklists), so we can release a version of Socket that has all these fixes?

**Comment by YorickPeterse** [comment]
@brixen No, we're not going to release any incomplete Gems. A substantial part of Addrinfo still has to be implemented, `Socket.ip_address_list` currently doesn't work (plus the implementation itself isn't really the best), largely due to Addrinfo being incomplete. Various parts of the other Socket APIs may be broken after my refactoring (hence the huge checklist of spec files to verify). Various parts have not yet been tested with IPv6, etc.

Those affected have been waiting since February at least, they can wait another 2 weeks or so for me to finish this.

**Comment by brixen** [comment]
@YorickPeterse things will always be incomplete, so by itself, that's not a sufficient reason to delay releasing something.

These are my two main questions: 1. There's a lot of Socket that isn't Addrinfo, so can Addrinfo be moved to a separate issue / PR? 2. Even with "spec review", we don't have 100% assurance of correctness, so how confident can we be with what we have spec'd now (eg do the current specs pass)?

Since RubySL is just gems, anyone can fork this, build their own gem and use it without waiting for either a Rubinius release or a release here. @saizai if you want to test what works for you, feel free to try that.

**Comment by YorickPeterse** [comment]
@brixen I'm not going to repeat myself (this will be the 3rd and final time): we're **not** going to release anything rubysl-socket related before it's done (and done properly). The changes required to support `Socket.ip_address_list` depend on Addrinfo being fully implemented which in turn depends on a bunch of other Socket changes, which in turn might depend on other changes, etc.

I literally do not understand why there's suddenly this pressure or need to release something. I've been working on this since February and now all of a sudden people want me to just release some half assed piece of code so something that has been broken since at least February _might_ work. More importantly as I've already stated plenty of times before I hope to get this over with before the end of the year. Breaking this PR up into smaller bits just because somebody can't wait another 2 weeks is a huge waste of my time.

We will release rubysl-socket once:

1. Addrinfo is fully implemented
2. Everything that we were lacking (basically everything added post 1.8) and that we can support has been added
3. IPv6 is supported and properly tested
4. All specs/behaviour matches MRI 2.2 behaviour
5. All specs pass on Travis for both MRI and Rubinius

I'll happily spend my Christmas holidays getting this done. I absolutely refuse to spend my Christmas holidays breaking up a 250+ commit pull request into 2 PRs, releasing a half assed Gem, and then trying to finish the above _just_ because users can't wait another 2 weeks. Seriously, have some bloody patience.

**Comment by YorickPeterse** [comment]
As far as I can tell currently all methods that we can support are implemented (unless I missed any). A few things remain:

* [ ] Certain nonblocking methods need to raise some IOWaitReadableWhatever error instead of `Errno::EINPROGRESS` or `Errno::EWOULDBLOCK` or whatever they were. This will need some changes in Rubinus itself.
* [ ] `RubySL::Socket::Helpers` has to be broken up in separate modules
* [ ] `RubySL::Socket::Foreign` needs to be cleaned up to use `memory_pointer` instead of `Rubinius::FFI::MemoryPointer` directly
* [ ] Code not dealing with FFI specifics (e.g. converting Addrinfos to Strings) should be moved out of `RubySL::Socket::Foreign`
* [ ] Rubinius currently segfaults when running `RUBYLIB=lib:. mspec spec/socket`, this should be fixed
* [ ] Rubinius should actually pass all specs, which it currently doesn't due to the above
* [ ] A proper README should be added

**Comment by digitalextremist** [comment]
:+1: @YorickPeterse

**Comment by YorickPeterse** [comment]
Dang, seems I missed the following Socket methods:

* [ ] `Socket.accept_loop`
* [ ] `Socket.getifaddrs`
* [ ] `Socket.getservbyport`
* [ ] `Socket.tcp`
* [ ] `Socket.tcp_server_loop`
* [ ] `Socket.tcp_server_sockets`
* [ ] `Socket.udp_server_loop`
* [ ] `Socket.udp_server_loop_on`
* [ ] `Socket.udp_server_recv`
* [ ] `Socket.udp_server_sockets`
* [ ] `Socket.unix`
* [ ] `Socket.unix_server_loop`
* [ ] `Socket.unix_server_socket`

**Comment by YorickPeterse** [comment]
Fixes #11 #10 #8 #7 #6 #5 #4 #3 #1

**Comment by YorickPeterse** [comment]
@brixen All done, we're passing all specs. Shall I leave you to reviewing about 10000 line changes, or shall we just merge things right away? :trollface:

**Comment by YorickPeterse** [comment]
FYI this also needs rubinius/rubinius@a84783dc3d0c408d078f763c4c4259be0b8712ba.

**Comment by YorickPeterse** [comment]
Since Travis refuses to build this pull request I'll be merging this (and praying OS X still works) some time this evening.

**Comment by jc00ke** [comment]
Awesome work @YorickPeterse!

**Comment by brixen** [comment]
:+1:

**Comment by saizai** [comment]
Which RBX versions have this update?

**Comment by YorickPeterse** [comment]
@saizai This has been available since Rubinius 3.8 (https://github.com/rubinius/rubinius/commit/34af1dbb3c24aab455df12e4ce1c0568f1110d47).

**Pull request merged**
